site_name: BARAM Page
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - i18n

nav:
  - Home: index.md
  - English:
    - Installation: en/installation.md
    - Release Notes: en/release_notes.md
    - baramFlow tutorial Guides:
      - Mixing Pipe: en/baramFlow_tutorial/2023-09-05-MixingPipe-post.md
      - Ahmed Body: en/baramFlow_tutorial/2023-09-05-AhmedBody-post.md
  - 한국어:
    - 설치: ko/baramFlow User Guide/install.md
    - 릴리즈 노트: ko/release_notes.md
    - baramFlow 튜토리얼:
      - index: ko/baramFlow_tutorial/index.md
      - 간단한 비압축성 유동 예제: ko/baramFlow_tutorial/simple_incompressible.md
      - 자동차 외부 유동 예제: ko/baramFlow_tutorial/car_external.md
      - 비정상 상태 유동 예제: ko/baramFlow_tutorial/transient.md
      - 열전달 예제: ko/baramFlow_tutorial/heatTransfer.md
      - 회전체 해석 예제: ko/baramFlow_tutorial/rotate.md
      - 다상유동 해석 예제: ko/baramFlow_tutorial/multiphase.md
      - 다공성 해석 예제: ko/baramFlow_tutorial/porous.md
      - 대기경계층 해석 예제: ko/baramFlow_tutorial/ABL.md
      - 비뉴턴유체 해석 예제: ko/baramFlow_tutorial/nonNewtonian.md
      - 화학종 해석 예제: ko/baramFlow_tutorial/species.md
      - 사용자 정의 스칼라 해석 예제: ko/baramFlow_tutorial/uds.md
      - 압축성 아음속 유동 해석 예제: ko/baramFlow_tutorial/subsonic.md
      - 밀도 기반 압축성 유동 해석 예제: ko/baramFlow_tutorial/densityBased.md
      - 일괄계산 유동 해석 예제: ko/baramFlow_tutorial/batchRun.md
    - baramFlow 유저 가이드:
      - intro: ko/baramFlow User Guide/intro.md
      - index: ko/baramFlow User Guide/index.md      
      - nomenclature: ko/baramFlow User Guide/nomenclature.md
      - general: ko/baramFlow User Guide/general.md
      - model: ko/baramFlow User Guide/model.md
      - material: ko/baramFlow User Guide/material.md      
      - boundary: ko/baramFlow User Guide/boundary.md
      - cellZone: ko/baramFlow User Guide/cellZone.md
      - monitor: ko/baramFlow User Guide/monitor.md
      - reference: ko/baramFlow User Guide/reference.md
      - numerical: ko/baramFlow User Guide/numerical.md
      - nextfoam: ko/baramFlow User Guide/nextfoam.md
      - initial: ko/baramFlow User Guide/initial.md
      - run condition: ko/baramFlow User Guide/runCondition.md
      - run: ko/baramFlow User Guide/run.md
      - report: ko/baramFlow User Guide/report.md
    - baramMesh 튜토리얼:
      - index: ko/baramMesh tutorial/index.md
      - Mixing Pipe : ko/baramMesh tutorial/mixingPipe.md
      - Ahmed Body : ko/baramMesh tutorial/Ahmed.md
      - Cantilever Beam : ko/baramMesh tutorial/cantilever.md
      - CHT : ko/baramMesh tutorial/CHTMesh.md
      - Weir : ko/baramMesh tutorial/weir.md
      - DrivAer : ko/baramMesh tutorial/drivAer.md
      - Porous Media : ko/baramMesh tutorial/porous.md
      - High Speed Train : ko/baramMesh tutorial/train.md
      - Rotating Fan in Room : ko/baramMesh tutorial/fanInRoom.md      
      - Propeller : ko/baramMesh tutorial/propeller.md
      - Sirocco Fan : ko/baramMesh tutorial/siroccofan.md
      - 3D Cavity : ko/baramMesh tutorial/cavity.md
      - Gap Refinement : ko/baramMesh tutorial/gap.md
      - Mixer : ko/baramMesh tutorial/mixer.md
      - Fan : ko/baramMesh tutorial/fan.md
      - Axi-symmetric Nozzle : ko/baramMesh tutorial/nozzle.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - assets/css/custom.css

plugins:
  - search:
  - awesome-pages:
  - section-index:
  - i18n:
      default_language: ko
      languages:
        en: Enlish
        ko: 한국어

markdown_extensions:
  - toc:
      toc_depth: 2