site_name: 바람 페이지
docs_dir: ../../docs/ko
site_dir: ../../site/ko

theme:
  name: material
  language: ko

nav:
  - 홈: index.md
  - 설치: installation.md
  - 공개 노트: release_notes.md
  - 바람플로우 튜토리얼 가이드 :
    - Mixing Pipe: baramFlow tutorial/2023-09-05-MixingPipe-post.md
    - Ahmed Body: baramFlow tutorial/2023-09-05-AhmedBody-post.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - assets/css/custom.css

extra:
  alternate:

    - name: Korean
      link: /baram-test-page/ko/
      lang: ko

    - name: English
      link: /baram-test-page/en/
      lang: en

plugins:
  - search:
      lang: ko
