site_name: 바람 페이지
docs_dir: ../../docs/ko
site_dir: ../../site/ko

theme:
  name: material
  language: ko

nav:
  - 홈: /docs/ko/index.md
  - 설치: /docs/ko/installation.md
  - 공개 노트: /docs/ko/release_notes.md
  - 바람플로우 튜토리얼 가이드 :
    - Mixing Pipe: /docs/ko/baramFlow tutorial/2023-09-05-MixingPipe-post.md
    - Ahmed Body: /docs/ko/baramFlow tutorial/2023-09-05-AhmedBody-post.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - assets/css/custom.css

extra:
  alternate:

    - name: Korean
      link: /ko/
      lang: ko

    - name: English
      link: /en/
      lang: en

plugins:
  - search:
      lang: ko
