site_name: BARAM Page
docs_dir: ../../docs/en
site_dir: ../../site/en

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Installation: installation.md
  - Release Notes: release_notes.md
  - baramFlow Tutorial Guide:
    - Ahmed Body: baramFlow tutorial/2023-09-05-AhmedBody-post.md
    - Mixing Pipe: baramFlow tutorial/2023-09-05-MixingPipe-post.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - assets/css/custom.css

extra:
  alternate:

    - name: Korean
      link: /baram-test-page/ko/
      lang: ko

    - name: English
      link: /baram-test-page/en/
      lang: en

plugins:
  - search:
      lang: en